# Generated by Django 3.2.10 on 2024-10-04 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0021_auto_20240915_2235'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.CharField(choices=[('client', 'client'), ('trainer', 'trainer'), ('super_admin', 'Super Admin')], default='client', max_length=255),
        ),
    ]
