# Generated by Django 5.0 on 2024-10-18 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0024_user_device_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='device_id',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
