# Generated by Django 3.2 on 2024-11-26 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0025_alter_user_device_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='PremiumProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_id', models.CharField(max_length=255, unique=True)),
                ('is_premium', models.BooleanField(default=False)),
            ],
        ),
    ]
