# Generated by Django 5.0 on 2024-10-15 12:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('train', '0029_exercise_instructions'),
        ('workout', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PerformExercise',
            new_name='workoutExercise',
        ),
        migrations.RenameField(
            model_name='set',
            old_name='perform_exercise',
            new_name='workoutExercise',
        ),
    ]
