# Generated by Django 5.0 on 2024-10-17 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workout', '0002_rename_performexercise_workoutexercise_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workout',
            name='user',
        ),
        migrations.RemoveField(
            model_name='workoutsession',
            name='user',
        ),
        migrations.AddField(
            model_name='workout',
            name='device_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='workoutsession',
            name='device_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
