# Generated by Django 5.0 on 2024-10-21 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workout', '0006_alter_workout_folder'),
    ]

    operations = [
        migrations.AddField(
            model_name='workout',
            name='notes',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
