# Generated by Django 5.0 on 2024-10-21 07:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('train', '0039_alter_exercise_instructions'),
        ('workout', '0007_workout_notes'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkoutHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_id', models.CharField(max_length=255)),
                ('highest_weight', models.DecimalField(decimal_places=2, max_digits=5)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('best_performance_set', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workout.setperformance')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workout.workoutsession')),
                ('workout', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workout.workout')),
            ],
        ),
        migrations.CreateModel(
            name='SetHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('set_number', models.PositiveIntegerField()),
                ('actual_kg', models.DecimalField(decimal_places=2, max_digits=5)),
                ('actual_reps', models.PositiveIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('exercise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='train.exercise')),
                ('workout_history', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='set_histories', to='workout.workouthistory')),
            ],
        ),
    ]
