# Generated by Django 5.0 on 2024-10-21 11:28

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workout', '0009_workoutsession_end_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='workoutsession',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
