# Generated by Django 5.0 on 2024-10-21 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workout', '0010_workoutsession_created_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workoutsession',
            name='end_time',
        ),
        migrations.AddField(
            model_name='workouthistory',
            name='workout_time',
            field=models.DurationField(blank=True, null=True),
        ),
    ]
