# Generated by Django 5.0 on 2024-10-21 14:34

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workout', '0011_remove_workoutsession_end_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='setperformance',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
