# Generated by Django 5.0 on 2024-11-05 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workout', '0013_sethistory_pr_sethistory_rm'),
    ]

    operations = [
        migrations.CreateModel(
            name='BodyPartMeasurement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_id', models.CharField(max_length=100)),
                ('arm_circumference', models.FloatField()),
                ('thigh_circumference', models.FloatField()),
                ('calf_circumference', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='CoreMeasurement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_id', models.CharField(max_length=100)),
                ('waist_circumference', models.FloatField()),
                ('hip_circumference', models.FloatField()),
                ('chest_circumference', models.FloatField()),
            ],
        ),
    ]
