# Generated by Django 3.2 on 2024-11-20 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workout', '0015_folder_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='folder',
            name='color',
            field=models.CharField(blank=True, max_length=7, null=True),
        ),
    ]
