# Generated by Django 5.0 on 2024-10-13 12:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('train', '0027_alter_routine_client'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='exercise',
            name='gif',
            field=models.FileField(blank=True, null=True, upload_to='exercise_videos/'),
        ),
        migrations.AlterField(
            model_name='session',
            name='trainer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
