# Generated by Django 5.0 on 2024-10-15 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('train', '0028_exercise_gif_alter_session_trainer'),
    ]

    operations = [
        migrations.AddField(
            model_name='exercise',
            name='instructions',
            field=models.CharField(blank=True, max_length=40),
        ),
    ]
