# Generated by Django 5.0 on 2024-10-15 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('train', '0030_remove_session_trainer_alter_set_setnum'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exercise',
            name='body_part',
            field=models.CharField(max_length=2),
        ),
    ]
