# Generated by Django 5.0 on 2024-10-15 18:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('train', '0031_alter_exercise_body_part'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='set',
            name='setgroup',
        ),
        migrations.AddField(
            model_name='set',
            name='Routine',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sets', to='train.routine'),
        ),
        migrations.AddField(
            model_name='set',
            name='exercise',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='setgroups', to='train.exercise'),
        ),
        migrations.AddField(
            model_name='set',
            name='order',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='set',
            name='previous',
            field=models.IntegerField(blank=True, null=True, verbose_name='Previous'),
        ),
        migrations.AddField(
            model_name='set',
            name='reps',
            field=models.IntegerField(blank=True, null=True, verbose_name='reps'),
        ),
        migrations.AlterField(
            model_name='set',
            name='setnum',
            field=models.IntegerField(blank=True, null=True, verbose_name='Set'),
        ),
        migrations.DeleteModel(
            name='Setgroup',
        ),
    ]
