# Generated by Django 5.0 on 2024-10-20 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('train', '0034_remove_set_routine_remove_session_routine_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='exercise',
            name='exercise_image',
            field=models.FileField(blank=True, null=True, upload_to='exercise_images/'),
        ),
    ]
