# Generated by Django 5.0 on 2024-10-20 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('train', '0036_alter_exercise_body_part'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exercise',
            name='instructions',
            field=models.CharField(blank=True, max_length=250),
        ),
    ]
