# Generated by Django 5.0 on 2024-10-20 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('train', '0038_alter_exercise_instructions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exercise',
            name='instructions',
            field=models.CharField(blank=True, max_length=800),
        ),
    ]
