# Generated by Django 4.0.6 on 2024-10-26 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('train', '0039_alter_exercise_instructions'),
    ]

    operations = [
        migrations.AddField(
            model_name='exercise',
            name='device_id',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
