# Generated by Django 5.0 on 2024-11-05 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('train', '0040_exercise_device_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='exercise',
            name='equipments',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
