# Generated by Django 5.0 on 2024-11-05 15:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('train', '0041_exercise_equipments'),
    ]

    operations = [
        migrations.RenameField(
            model_name='exercise',
            old_name='equipments',
            new_name='equipment',
        ),
    ]
