# Generated by Django 3.2 on 2024-12-18 17:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('knet', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='KnetPayment',
        ),
    ]
