# Generated by Django 3.2 on 2024-12-18 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('knet', '0002_delete_knetpayment'),
    ]

    operations = [
        migrations.CreateModel(
            name='KnetTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('track_id', models.CharField(max_length=50, unique=True)),
                ('payment_id', models.CharField(blank=True, max_length=50, null=True)),
                ('amount', models.DecimalField(decimal_places=3, max_digits=10)),
                ('result', models.CharField(choices=[('INITIATED', 'Initiated'), ('CAPTURED', 'Captured'), ('NOT CAPTURED', 'Not Captured'), ('CANCELED', 'Canceled'), ('HOST TIMEOUT', 'Host Timeout'), ('ERROR', 'Error')], default='INITIATED', max_length=20)),
                ('auth', models.CharField(blank=True, max_length=50, null=True)),
                ('ref', models.CharField(blank=True, max_length=50, null=True)),
                ('tran_id', models.CharField(blank=True, max_length=50, null=True)),
                ('error_code', models.CharField(blank=True, max_length=50, null=True)),
                ('error_text', models.TextField(blank=True, null=True)),
                ('encrypted_response', models.TextField(blank=True, null=True)),
                ('decrypted_response', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
