# Generated by Django 3.2 on 2024-12-18 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('knet', '0003_knettransaction'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='knettransaction',
            name='error_code',
        ),
        migrations.RemoveField(
            model_name='knettransaction',
            name='error_text',
        ),
        migrations.AddField(
            model_name='knettransaction',
            name='status',
            field=models.CharField(default='INITIATED', max_length=20),
        ),
        migrations.AlterField(
            model_name='knettransaction',
            name='result',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
